# Generated by Django 5.0.2 on 2024-02-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('month', models.CharField(default='', max_length=10)),
                ('record_number', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
            ],
        ),
    ]
