# Generated by Django 5.0.2 on 2024-02-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record_db',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
