# Generated by Django 5.0.2 on 2024-04-10 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_alter_record_db_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record_DB',
            new_name='Cpi_db',
        ),
    ]
