# Generated by Django 5.0.2 on 2024-04-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_unemp_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntRates_db',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(default=0)),
                ('month', models.CharField(default='', max_length=10)),
                ('record_number', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
            ],
        ),
    ]
