# Generated by Django 5.0.2 on 2024-04-11 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_intrates_db'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cpi_db',
            new_name='Cpi_db_USA',
        ),
        migrations.RenameModel(
            old_name='IntRates_db',
            new_name='IntRates_db_USA',
        ),
        migrations.RenameModel(
            old_name='Unemp_db',
            new_name='Unemp_db_USA',
        ),
    ]
