# Generated by Django 5.0.2 on 2024-04-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_rename_cpi_db_cpi_db_usa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpi_db_CAD',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(default=0)),
                ('month', models.CharField(default='', max_length=10)),
                ('record_number', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Cpi_db_EURO',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(default=0)),
                ('month', models.CharField(default='', max_length=10)),
                ('record_number', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Cpi_db_JPY',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(default=0)),
                ('month', models.CharField(default='', max_length=10)),
                ('record_number', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='IntRates_db_CAD',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(default=0)),
                ('month', models.CharField(default='', max_length=10)),
                ('record_number', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='IntRates_db_EURO',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(default=0)),
                ('month', models.CharField(default='', max_length=10)),
                ('record_number', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='IntRates_db_JPY',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(default=0)),
                ('month', models.CharField(default='', max_length=10)),
                ('record_number', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
            ],
        ),
    ]
