# Generated by Django 5.0.4 on 2024-06-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_cpi_db_cad_cpi_db_euro_cpi_db_jpy_intrates_db_cad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpi_db_USA_yearmean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('year_mean', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Cpi_db_CAD',
        ),
        migrations.DeleteModel(
            name='Cpi_db_EURO',
        ),
        migrations.DeleteModel(
            name='Cpi_db_JPY',
        ),
    ]
