# Generated by Django 5.0.4 on 2024-06-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_cpi_db_usa_yearmean_delete_cpi_db_cad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntRates_db_CAD_yearmean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('year_mean', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IntRates_db_EURO_yearmean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('year_mean', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IntRates_db_JPY_yearmean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('year_mean', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IntRates_db_USA_yearmean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('year_mean', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Unemp_db_USA_yearmean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('year_mean', models.IntegerField(default=0)),
            ],
        ),
    ]
